In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Refined.csv")
df

Unnamed: 0  race  gender  age  time_in_hospital  num_lab_procedures  \
0               1     1       0    2                 3                  59   
1               2     2       0    3                 2                  11   
2               3     1       1    4                 2                  44   
3               4     1       1    5                 1                  51   
4               5     1       1    6                 3                  31   
...           ...   ...     ...  ...               ...                 ...   
98047      101761     2       1    8                 3                  51   
98048      101762     2       0    9                 5                  33   
98049      101763     1       1    8                 1                  53   
98050      101764     1       0    9                10                  45   
98051      101765     1       1    8                 6                  13   

       num_procedures  num_medications  number_emergency  diag_1  diag_2  \
0                   0               18                 0  276.00  250.01   
1                   5               13                 0  648.00  250.00   
2                   1               16                 0    8.00  250.43   
3                   0                8                 0  197.00  157.00   
4                   6               16                 0  414.00  411.00   
...               ...              ...               ...     ...     ...   
98047               0               16                 0  250.13  291.00   
98048               3               18                 0  560.00  276.00   
98049               0                9                 0   38.00  590.00   
98050               2               21                 0  996.00  285.00   
98051               3                3                 0  530.00  530.00   

       diag_3  change  diabetesMed  readmitted  
0       255.0       1            1           0  
1        18.0       0            1           0  
2       403.0       1            1           0  
3       250.0       1            1           0  
4       250.0       0            1           0  
...       ...     ...          ...         ...  
98047   458.0       1            1           0  
98048   787.0       0            1           0  
98049   296.0       1            1           0  
98050   998.0       1            1           0  
98051   787.0       0            0           0  

[98052 rows x 15 columns]

In [ ]:
df["diag_1"].value_counts()
df["diag_1"]=df["diag_1"].drop(df[df["diag_1"]=="?"].index,axis=0)
df["diag_2"]=df["diag_2"].drop(df[df["diag_2"]=="?"].index,axis=0)
df["diag_3"]=df["diag_3"].drop(df[df["diag_3"]=="?"].index,axis=0)

In [ ]:
df["diag_1"]=df["diag_1"].astype(float)
df["diag_2"]=df["diag_2"].astype(float)
df["diag_3"]=df["diag_3"].astype(float)
df=df.dropna()

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:0 if x<=139 else x)


In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:1 if  x>140 and x<=239 else x)


In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:2 if  x>239 and x<=279 else x)


In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:3 if  x>279 and x<=289 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:4 if  x>289 and x<=319 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:5 if  x>319 and x<=389 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:6 if  x>389 and x<=459 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:7 if  x>459 and x<=519 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:8 if  x>519 and x<=579 else x)

In [ ]:
df["diag_1"]=df["diag_1"].apply(lambda x:9 if  x>=580 and x<=629 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:10 if  x>=630 and x<=679 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:11 if  x>=680 and x<=709 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:12 if  x>=710 and x<=739 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:13 if  x>=740 and x<=759 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:14 if  x>=760 and x<=779 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:15 if  x>=780 and x<=799 else x)
df["diag_1"]=df["diag_1"].apply(lambda x:16 if  x>=800 and x<=999 else x)
df

Unnamed: 0  race  gender  age  time_in_hospital  num_lab_procedures  \
0               1     1       0    2                 3                  59   
1               2     2       0    3                 2                  11   
2               3     1       1    4                 2                  44   
3               4     1       1    5                 1                  51   
4               5     1       1    6                 3                  31   
...           ...   ...     ...  ...               ...                 ...   
98047      101761     2       1    8                 3                  51   
98048      101762     2       0    9                 5                  33   
98049      101763     1       1    8                 1                  53   
98050      101764     1       0    9                10                  45   
98051      101765     1       1    8                 6                  13   

       num_procedures  num_medications  number_emergency  diag_1  diag_2  \
0                   0               18                 0     2.0  250.01   
1                   5               13                 0    10.0  250.00   
2                   1               16                 0     0.0  250.43   
3                   0                8                 0     1.0  157.00   
4                   6               16                 0     6.0  411.00   
...               ...              ...               ...     ...     ...   
98047               0               16                 0     2.0  291.00   
98048               3               18                 0     8.0  276.00   
98049               0                9                 0     0.0  590.00   
98050               2               21                 0    16.0  285.00   
98051               3                3                 0     8.0  530.00   

       diag_3  change  diabetesMed  readmitted  
0       255.0       1            1           0  
1        18.0       0            1           0  
2       403.0       1            1           0  
3       250.0       1            1           0  
4       250.0       0            1           0  
...       ...     ...          ...         ...  
98047   458.0       1            1           0  
98048   787.0       0            1           0  
98049   296.0       1            1           0  
98050   998.0       1            1           0  
98051   787.0       0            0           0  

[98052 rows x 15 columns]

In [ ]:
#replace diag 2
df["diag_2"]=df["diag_2"].apply(lambda x:9 if  x>=580 and x<=629 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:10 if  x>=630 and x<=679 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:11 if  x>=680 and x<=709 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:12 if  x>=710 and x<=739 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:13 if  x>=740 and x<=759 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:14 if  x>=760 and x<=779 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:15 if  x>=780 and x<=799 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:16 if  x>=800 and x<=999 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:0 if x<=139 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:1 if  x>140 and x<=239 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:2 if  x>239 and x<=279 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:3 if  x>279 and x<=289 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:4 if  x>289 and x<=319 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:5 if  x>319 and x<=389 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:6 if  x>389 and x<=459 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:7 if  x>459 and x<=519 else x)
df["diag_2"]=df["diag_2"].apply(lambda x:8 if  x>519 and x<=579 else x)

In [ ]:
#replace diag_2
df["diag_3"]=df["diag_3"].apply(lambda x:0 if x<=139 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:1 if  x>140 and x<=239 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:2 if  x>239 and x<=279 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:3 if  x>279 and x<=289 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:4 if  x>289 and x<=319 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:5 if  x>319 and x<=389 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:6 if  x>389 and x<=459 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:7 if  x>459 and x<=519 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:8 if  x>519 and x<=579 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:9 if  x>=580 and x<=629 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:10 if  x>=630 and x<=679 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:11 if  x>=680 and x<=709 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:12 if  x>=710 and x<=739 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:13 if  x>=740 and x<=759 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:14 if  x>=760 and x<=779 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:15 if  x>=780 and x<=799 else x)
df["diag_3"]=df["diag_3"].apply(lambda x:16 if  x>=800 and x<=999 else x)
df

Unnamed: 0  race  gender  age  time_in_hospital  num_lab_procedures  \
0               1     1       0    2                 3                  59   
1               2     2       0    3                 2                  11   
2               3     1       1    4                 2                  44   
3               4     1       1    5                 1                  51   
4               5     1       1    6                 3                  31   
...           ...   ...     ...  ...               ...                 ...   
98047      101761     2       1    8                 3                  51   
98048      101762     2       0    9                 5                  33   
98049      101763     1       1    8                 1                  53   
98050      101764     1       0    9                10                  45   
98051      101765     1       1    8                 6                  13   

       num_procedures  num_medications  number_emergency  diag_1  diag_2  \
0                   0               18                 0     2.0     2.0   
1                   5               13                 0    10.0     2.0   
2                   1               16                 0     0.0     2.0   
3                   0                8                 0     1.0     1.0   
4                   6               16                 0     6.0     6.0   
...               ...              ...               ...     ...     ...   
98047               0               16                 0     2.0     4.0   
98048               3               18                 0     8.0     2.0   
98049               0                9                 0     0.0     0.0   
98050               2               21                 0    16.0     3.0   
98051               3                3                 0     8.0     8.0   

       diag_3  change  diabetesMed  readmitted  
0         2.0       1            1           0  
1         0.0       0            1           0  
2         6.0       1            1           0  
3         2.0       1            1           0  
4         2.0       0            1           0  
...       ...     ...          ...         ...  
98047     6.0       1            1           0  
98048    15.0       0            1           0  
98049     4.0       1            1           0  
98050    16.0       1            1           0  
98051    15.0       0            0           0  

[98052 rows x 15 columns]

In [ ]:
df1=pd.read_csv("/content/drive/MyDrive/sairam.csv")
df1.drop(columns="diag_2",axis=1,inplace=True)
df1.drop(columns="diag_3",axis=1,inplace=True)

In [ ]:
X = df1.iloc[:, :-1].values
y = df1.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 1  1  4 ...  8  1  1]
 [ 2  1  8 ...  8  1  1]
 [ 1  0  6 ...  7  1  1]
 ...
 [ 1  0  8 ...  7  1  1]
 [ 1  0  8 ...  7  1  1]
 [ 1  1  8 ... 15  1  1]]
[0 0 0 ... 0 0 1]
[[ 1  1  8 ...  6  1  1]
 [ 2  1  6 ... 15  0  1]
 [ 1  1  8 ... 16  0  0]
 ...
 [ 2  0  8 ...  1  0  0]
 [ 1  0  6 ...  4  0  1]
 [ 1  0 10 ... 15  1  1]]
[0 0 1 ... 0 0 0]


In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.45438743  1.07911387 -2.00000386 ...  0.16183918  1.08263507
   0.55158096]
 [ 0.99473456  1.07911387  0.5636838  ...  0.16183918  1.08263507
   0.55158096]
 [-0.45438743 -0.92668626 -0.71816003 ... -0.06708619  1.08263507
   0.55158096]
 ...
 [-0.45438743 -0.92668626  0.5636838  ... -0.06708619  1.08263507
   0.55158096]
 [-0.45438743 -0.92668626  0.5636838  ... -0.06708619  1.08263507
   0.55158096]
 [-0.45438743  1.07911387  0.5636838  ...  1.76431677  1.08263507
   0.55158096]]
[[-0.45438743  1.07911387  0.5636838  ... -0.29601156  1.08263507
   0.55158096]
 [ 0.99473456  1.07911387 -0.71816003 ...  1.76431677 -0.92367228
   0.55158096]
 [-0.45438743  1.07911387  0.5636838  ...  1.99324214 -0.92367228
  -1.81297048]
 ...
 [ 0.99473456 -0.92668626  0.5636838  ... -1.4406384  -0.92367228
  -1.81297048]
 [-0.45438743 -0.92668626 -0.71816003 ... -0.75386229 -0.92367228
   0.55158096]
 [-0.45438743 -0.92668626  1.84552764 ...  1.76431677  1.08263507
   0.55158096]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15182  2209]
 [ 1903   317]]


0.7903217581969303

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(criterion = 'entropy',random_state=0)
model.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[17353    38]
 [ 2211     9]]


0.8853194635663658

In [ ]:
def train(model,x,y):
    x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)
    model.fit(x_train,y_train)
    pred=model.predict(x_test)
    # cv_score= cross_val_score(model,x,y,cv=3,scoring="accuracy").mean()
    acc=accuracy_score(y_test,pred)
    # print("CV_score: ",cv_score)
    print("ACCURACY: ",acc)
    print(confusion_matrix(y_test,pred))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(criterion = 'entropy',random_state=0)
train(model,X_train, y_train)

ACCURACY:  0.8849625210341135
[[17347    25]
 [ 2231     8]]


In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [ ]:
model = GaussianNB()

# fit the model with the training data
model.fit(X_train, y_train)


GaussianNB()

In [ ]:
# predict the target on the train dataset
predict_train = model.predict(X_train)
print('Target on train data',predict_train) 

Target on train data [0 0 0 ... 0 0 0]


In [ ]:
# Accuray Score on train dataset
accuracy_train = accuracy_score(y_train,predict_train)
print('accuracy_score on train dataset : ', accuracy_train)

accuracy_score on train dataset :  0.8785839038258054


In [ ]:
# predict the target on the test dataset
predict_test = model.predict(X_test)
print('Target on test data',predict_test)

Target on test data [0 0 0 ... 0 0 0]


In [ ]:
#  Accuracy Score on test dataset
accuracy_test = accuracy_score(y_test,predict_test)
print('accuracy_score on test dataset : ', accuracy_test)

accuracy_score on test dataset :  0.8796593748406507
